modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="random_blocks"
version="1.0.0"
displayName="Random Blocks"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="S, MCreator"
description='''
Everythings you want...
'''

[[dependencies.random_blocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




